#!/usr/bin/env bash
#PBS -l mem=4G
#PBS -q omp
#PBS -l ncpus=2
#PBS -l walltime=2:00:00
#PBS -m n

########################################
##      Load environment              ##
########################################

# Load tool : path to the tool
. /appli/bioinfo/anvio/8_dev/env.sh

# Path to working directory
cd $iron_nos/01_FASTA

# Reformat fasta files
for i in FASTA/*.fa
do prefix=$(basename $i .fa)
anvi-script-reformat-fasta $i -o REFORMATED/"$prefix"_reformated.fa --prefix $prefix --simplify-names -r reformated.txt
done

