#!/usr/bin/env bash
#PBS -l mem=50G
#PBS -q omp
#PBS -l ncpus=32
#PBS -l walltime=4:00:00
#PBS -m n

# Load Singularity
. /etc/profile.d/modules.sh
module purge
module load singularity/3.4.1

# Load Checkm2 environment
. /appli/bioinfo/checkm2/1.0.1/env.sh

# Checkm2 singularity container
CHECKM2_SIF=/appli/bioinfo/checkm2/1.0.1/checkm2-1.0.1.sif

# Il faut créer des variables pour les chemins des dossiers pour cette commande
path=/home/datawork-lmee-intranet-nos/IRON2MI/LUDIVINE/01_metagenomic_mat/MARION
inputdir=$path/01_FASTA/REFORMATED
outputdir=$path/02_QUALITY/CheckM2

cd $path

#Run Checkm2
singularity run -B /appli -B /home/ref-bioinfo/ifremer/sebimer/tool-specific-banks/checkm2/1.0.1/ -B $DATAWORK  ${CHECKM2_SIF} checkm2 predict --thread 30 --input $inputdir -x fa --output-directory $outputdir >& $path/00_LOGS/CheckM2.log 2>&1




