
### CheckM2 on DATARMOR server is a singularity (not like an environnement that you load at the begenning of the script)

# Load singularity (code not shown)

# Checkm2 singularity container
CHECKM2_SIF=path/to/CHECKM2/SIF

# Create variable for work directory pathway
inputdir=path/to/FASTA/REFORMATED
outputdir=path/to/output/CheckM2

# Run Checkm2
singularity run -B /appli -B path/to/tool/checkm2/1.0.1/ -B $DATAWORK  ${CHECKM2_SIF} checkm2 predict --thread 30 --input $inputdir -x fa --output-directory $outputdir 




