#!/usr/bin/env bash
#PBS -l mem=50G
#PBS -q omp
#PBS -l ncpus=32
#PBS -l walltime=4:00:00
#PBS -m n

# Load Singularity
. /etc/profile.d/modules.sh
module purge
module load singularity/3.4.1

# Load Checkm2 environment
. /appli/bioinfo/checkm2/1.0.1/env.sh

# Checkm2 singularity container
CHECKM2_SIF=/appli/bioinfo/checkm2/1.0.1/checkm2-1.0.1.sif

# Creat variable for work directory pathway
inputdir=$iron_nos/01_FASTA/REFORMATED
outputdir=$iron_nos/02_QUALITY/CheckM2

cd $iron_nos

#Run Checkm2
singularity run -B /appli -B /home/ref-bioinfo/ifremer/sebimer/tool-specific-banks/checkm2/1.0.1/ -B $DATAWORK  ${CHECKM2_SIF} checkm2 predict --thread 30 --input $inputdir -x fa --output-directory $outputdir >& $iron_nos/00_LOGS/CheckM2.log 2>&1




