
### This script creates a symbolic link from our MAGs to our workspace.

# Create a file with all Zetaproteobacteria MAGs
grep "Zetaproteobacteria" ../MAGs_all.tsv > ../zeta_all.tsv

# Create a file with medium quality Zetaproteobacteria MAGs
grep "Zetaproteobacteria" ../MAGs_MQ.tsv > ../zeta_MQ.tsv
# MAGs MQ c'est complétion >70% et redondance <5%

# Loop to make symbolic link of MAGs
cut -f1 ../MAGs_MQ.tsv | while read i ; do ln -s ../../01_FASTA/REFORMATED/"$i".fa . ; done

cd ../ZETA_MQ
cut -f1 ../zeta_MQ.tsv | while read i ; do ln -s ../../01_FASTA/REFORMATED/"$i".fa . ; done
